### ISSUE TITLE
Spring4D

### ISSUE THREAD

**Issue by jaclas** [sempare/sempare-delphi-streams#1]
Does this library work with the Spring4Delphi collections? If not, are there plans for such cooperation?
I only use the Spring collection (like many programmers) and this cooperation would be useful.

**Comment by sempare** [comment]
Hi,
I've added support for the spring4d IEnumerable<T> in the dev branch which will give full provision.

SEMPARE_STREAMS_SPRING4D_SUPPORT must be defined as a compiler option, or define uncommented in the Sempare.Streams.inc and must add 'Sempare.Streams.Spring4d' as unit in the uses clause to include the helper. I might merge that into the main as adding the extra unit can be annoying every time. Do you have any opinions?

**Comment by jaclas** [comment]
I wouldn't combine it, because then you will force the use of the S4D, and yet the lack of dependences is better. 
Adding uses is not a problem.

**Comment by sempare** [comment]
Thanks for your feedback. That was my feeling, but I was just thinking of convenience as there is the 'define' and the 'uses' where one mechanism would be sufficient... actually. I'm being silly. I think I just need the define for the tests... but I'll review later...

**Comment by sempare** [comment]
I found what I wanted to do... in the Sempare.Streams.Spring4d, I included a reference onto the Stream entry point. That removed the need for including Sempare.Streams itself, which I disliked. I prefer having minimal 'uses'... Feel free to provide any other feedback. Thanks.
